import React, { ReactElement } from "react";
import Head from "next/head";

const PageHeader = (): ReactElement => {
  return (
    <Head>
      <title>Console Log</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageHeader;
