import React, { ReactElement } from "react";
import Head from "next/head";

interface PageHeaderProps {
  title: string;
}

const PageHeader = ({ title }: PageHeaderProps): ReactElement => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageHeader;
